version: "3.8"

services:
  api:
    build: .
    container_name: gofit-ecommerce_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
