version: "3.8"

services:
  api:
    build: .
    container_name: gofit-ecommerce_api
    restart: always
    ports:
      - "4199:4199"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
